account/urls.py
from django.urls import path
from .views import *

app_name = "account"

urlpatterns = [
    path("register", register__view, name="register"),
    path("login", login__view, name="login"),
    path("logout", logout__view, name="logout"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from article.views import *

urlpatterns = [
    path("", home__view, name="home"),
    path("about/", about__view, name="about"),
    path("contact/", contact__view, name="contact"),
    path("articles/", articles__view, name="articles"),
    path("article-detail/<int:id>", article__detail__view, name="article-detail"),
    path("addarticle/", addarticle__view, name="addarticle"),
    path("update/<int:id>", article__update__view, name="update"),
    path("delete/<int:id>", article__delete__view, name="delete"),
    path("dashboard/", dashboard__view, name="dashboard"),
    path("account/", include("account.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
# Author title content created_date >> Article


class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="Yazar")
    title = models.CharField(max_length=150, verbose_name="Başlıq")  # input
    content = RichTextField(verbose_name="Məzmun")  # textarea
    created_date = models.DateTimeField(auto_now_add=True)
    image = models.FileField(upload_to="Article Images",blank=True, null=True,verbose_name="Şəkil")

    def __str__(self):
        return f"{self.title} | {self.author}"

account/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, label="İstifadəçi adı")
    password = forms.CharField(max_length=10, label="Şifrə", widget=forms.PasswordInput)
    

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=30, label="İstifadəçi adı")
    password = forms.CharField(max_length=10, label="Şifrə", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=10, label="Şifrəni təsdiqlə", widget=forms.PasswordInput)
    
    def clean(self):
        username = self.cleaned_data["username"]
        password = self.cleaned_data["password"]
        confirm = self.cleaned_data["confirm"]
        
        
        if password and confirm and password !=confirm:
            raise forms.ValidationError("Şifrələr eyni deyil!!")
        
        values = {
            "username": username,
            "password": password
        }
        
        return values
    
    

article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "image"]
        

account/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
# Create your views here.


def register__view(request):
    form = RegisterForm(request.POST or None)
    
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        
        newUser = User(username = username)
        newUser.set_password(password)
        
        newUser.save()
    
        login(request, newUser)
        messages.success(request, "Siz uğurla qeydiyyatdan keçdiniz...")
        
        return redirect("home")
    context = {"form": form}
    return render(request, "register.html", context)


def login__view(request):
    form = LoginForm(request.POST or None)
    
    context = {"form": form}
    
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user is None:
            return render(request, "login.html", context)
        
        login(request, user)
        messages.success(request, "Siz uğurla daxil oldunuz...")
        return redirect("home")
    return render(request, "login.html", context)


def logout__view(request):
    logout(request)
    return redirect("home")

article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
def home__view(request):
    return render(request, "index.html")


def about__view(request):
    return render(request, "about.html")


def contact__view(request):
    return render(request, "contact.html")


@login_required(login_url="account:login")
def articles__view(request):
    articles = Article.objects.all()
    return render(request, "articles.html", {"articles": articles})


@login_required(login_url="account:login")
def article__detail__view(request, id):
    # article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article, id=id)
    # print(article)
    return render(request, "article-detail.html", {"article": article})


@login_required(login_url="account:login")
def addarticle__view(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        # save() -> hemise commiti True olaraq qebul edir.
        messages.success(request, "Məqaləniz uğurla əlavə olundu...")
        return redirect("dashboard")

    context = {"form": form}
    return render(request, "addarticle.html", context)


@login_required(login_url="account:login")
def article__update__view(request, id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)

    if form.is_valid():
        # article = form.save(commit=False)
        # article.author = request.user
        article.save()
        messages.success(request, "Məqaləniz uğurla güncəlləndi...")
        return redirect("dashboard")

    context = {"form": form}
    return render(request, "update.html", context)


@login_required(login_url="account:login")
def article__delete__view(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    messages.success(request, "Məqaləniz uğurla silindi...")
    return redirect("dashboard")

@login_required(login_url="account:login")
def dashboard__view(request):
    articles = Article.objects.filter(author=request.user)
    return render(request, "dashboard.html", {"articles": articles})

templates/about.html
{% extends "base.html" %}


{% block page__title %}
    About Page
{% endblock page__title %}
    

{% block body %}
<h1>About Page</h1>

{% endblock body %}

templates/addarticle.html
{% extends "base.html" %}


{% block page__title %}
    Məqalə əlavə et
{% endblock page__title %}
    


{% block body %}
    <h2>Məqalə əlavə et</h2><br>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form.as_p}}

        <br>
        <button class="btn">Əlavə et</button>
    </form>
{% endblock body %}
    

templates/article-detail.html
{% extends "base.html" %}


{% block page__title %}
Məqalə Detal
{% endblock page__title %}



{% block body %}
<div class="articles">

    <h3>Yazar: {{article.author}}</h3>
    <h4>Başlıq: {{article.title}}</h4>
    <p>Məzmun: {{article.content|safe}}</p>
    <small>Paylaşıldığı tarixi: {{article.created_date}}</small>
    <br><br>
    {% if article.image %}
    <img src="{{article.image.url}}" alt="">
    {% endif %}
    <hr>
</div>
{% endblock body %}

templates/articles.html
{% extends "base.html" %}


{% block page__title %}
Məqalələrimiz
{% endblock page__title %}



{% block body %}
<h2>Məqalələrimiz</h2>

<div class="articles">
    <ul>
        {% for article in articles %}
        <li>
            <h3>{{article.author}}</h3>
            <h4><a href="{% url 'article-detail' article.id %}">{{article.title}}</a></h4>
            <p>{{article.content|safe|truncatechars:70}}</p>
            <small>{{article.created_date}}</small>
        </li>
        <hr>
        {% endfor %}
    </ul>
</div>
{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="shortcut icon" href="{% static 'logo.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>

        {% block page__title %}
        MY SITE
        {% endblock page__title %}

    </title>
</head>

<body>

    <div class="navbar">
        <div class="nav__logo">
            <img src="{% static 'logo.png' %}" alt="">
        </div>

        <div class="nav__links">
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
                
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'articles' %}">Məqalələr</a></li>
                    <li><a href="{% url 'dashboard' %}"><i class="fa-solid fa-user"></i></a></li>
                    <li><a href="{% url 'account:logout' %}"><i class="fa-solid fa-right-from-bracket"></i></a></li>
                {% else %}
                    <li><a href="{% url 'account:login' %}">Login</a></li>
                    <li><a href="{% url 'account:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </div>

    {% if messages %}
      
      {% for message in messages %}
        {% if message.tags == "warning" %}
            <div class="alert__warning">{{message}}</div>
        {% else %}
            <div class="alert__success">{{message}}</div>
        {% endif %}
      {% endfor %}
        
    {% endif %}

    <div class="container">
        {% block body %}
        <h1>Salam Millet</h1>
        {% endblock body %}

    </div>

</body>

</html>

templates/contact.html
{% extends "base.html" %}


{% block page__title %}
    Contact Page
{% endblock page__title %}
    

{% block body %}
<h1>Contact Page</h1>

{% endblock body %}

templates/dashboard.html
{% extends "base.html" %}


{% block page__title %}
    İstifadəçi Paneli
{% endblock page__title %}
    


{% block body %}
{% if request.user.is_authenticated %}
    <div class="user__info">
        <h2>Xoş gəldiniz, <span>{{request.user.username}}</span></h2>
    </div>
{% else %}
    <div class="user__info">
        <h2>Giriş etməmisiz...</h2>
    </div>
{% endif %}

<div class="articles">
    <ul>
        
        {% for article in articles %}
            <li>
                <h3>{{article.author}}</h3>
                <h4><a href="{% url 'article-detail' article.id %}">{{article.title}}</a></h4>
                <p>{{article.content|safe|truncatechars:70}}</p>
                <small>{{article.created_date}}</small>
                <br><br>
                <a href="{% url 'update' article.id %}"><i class="fa-solid fa-gear"></i></a>
                <a href="{% url 'delete' article.id %}"><i class="fa-solid fa-trash"></i></a>
                <br>
            </li>
            <br>
            <hr>
            <br>
        {% endfor %}
    </ul>
</div>

<br>
<a href="{% url 'addarticle' %}"><button class="btn">Məqalə əlavə et</button></a>
{% endblock body %}

templates/index.html
{% extends "base.html" %}


{% block page__title %}
    Ana Səhifə
{% endblock page__title %}
    

{% block body %}



<h1>Ana Səhifə</h1>


{% endblock body %}

templates/login.html
{% extends "base.html" %}

{% block page__title %}
    Login Page
{% endblock page__title %}

{% block body %}
    <h2>Login Page</h2>

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{form.username.id_for_label}}">İstifadəçi adı</label>
            {{form.username}}
        </div>
        <div class="form-group">
            <label for="{{form.password.id_for_label}}">Şifrə</label>
            {{form.password}}
        </div>
        <br>
        <button class="btn">Daxil ol</button>
    </form>
{% endblock body %}
    

templates/register.html
{% extends "base.html" %}

{% block page__title %}
    Register Page
{% endblock page__title %}

{% block body %}
    <h2>Register Page</h2>

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{form.username.id_for_label}}">İstifadəçi adı</label>
            {{form.username}}
        </div>
        <div class="form-group">
            <label for="{{form.password.id_for_label}}">Şifrə</label>
            {{form.password}}
        </div>
        <div class="form-group">
            <label for="{{form.confirm.id_for_label}}">Şifrəni Təsdiqlə</label>
            {{form.confirm}}
        </div>
        <br>
        <button class="btn">Qeydiyyatdan Keç</button>
    </form>
{% endblock body %}

templates/update.html
{% extends "base.html" %}


{% block page__title %}
    Məqalə güncəllə
{% endblock page__title %}
    


{% block body %}
    <h2>Məqalə güncəllə</h2><br>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form.as_p}}

        <br>
        <button class="btn">güncəllə</button>
    </form>
{% endblock body %}
    